HOSTS:
  el7:
    roles:
      - server
      # roles migrated from now-removed el6 node(s): 
      - client
      - default
      - master
    platform:   el-7-x86_64
    image:      rhel-7-v20170426
    hypervisor: google
CONFIG:
  ssh:
    keepalive: true
    keepalive_interval: 10
  log_level: verbose
  type:      aio
  keyfile:  ADD_ME
  gce_project: ADD_ME
  gce_keyfile: ADD_ME
  gce_email: ADD_ME
